import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserIdProvider } from "@/components/contexts/userIdContext";
import { SetPagesProvider } from "@/components/contexts/setPageUserContext";
import { SetPagePostsProvider } from "@/components/contexts/setPagePostsContext";
import { ActiveShowPostsUpProvider } from "@/components/contexts/activeShowPostsUpStoryContext";
import { ActiveShowPostsDownProvider } from "@/components/contexts/activeShowPostsDownStoryContext";
import { ActiveMenuProvider } from "@/components/contexts/activeToggleMenu";
import { ActiveProvider } from "@/components/contexts/activeModalCreatPostContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head></head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> 
        <UserIdProvider>
        <SetPagesProvider>
        <SetPagePostsProvider>
          <ActiveShowPostsUpProvider>
          <ActiveShowPostsDownProvider>
          <ActiveMenuProvider>
          <ActiveProvider>
          {children}
          </ActiveProvider>
          </ActiveMenuProvider>
          </ActiveShowPostsDownProvider>
          </ActiveShowPostsUpProvider>  
        </SetPagePostsProvider>
        </SetPagesProvider>
        </UserIdProvider>
      </body>
    </html>
  );
}
